# @package _global_

defaults:
  - _self_
  - data: ljspeech_16kHz.vctk_48kHz
  - model: dual_cyclegan

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple: 
        format: '[%(asctime)s][%(module)s: %(lineno)d] %(message)s'

out_dir: 
checkpoint_path: 